---
title: "Clustering Universities - Brazil"
author: "Kássio Camelo"
date: "25 de março de 2019"
output: 
  html_document:
    code_folding: "hide"
    css: size.css
    theme: cerulean
    highlight: pygments
    includes:
      after_body: footer.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r cluster_federais}
library(dplyr)
library(rgdal)
library(leaflet)
library(rstudioapi) 
library(readxl)
library(tidyverse)
library(readr)
library(DT)

setwd("C:/Users/geisa.vasconcelos/workspace/trabalho/cluster_federais/")

IES<-read.csv2("C:/Users/geisa.vasconcelos/Downloads/microdados_censo/DADOS/DM_IES.CSV",sep="|")

IES = as.data.frame(IES, stringsAsFactors = FALSE)
IES = IES[c("NO_IES", "NO_MUNICIPIO_IES", "IN_CAPITAL_IES", "QT_TEC_FUND_INCOMP_FEM",
            "QT_TEC_FUND_INCOMP_MASC","QT_TEC_FUND_COMP_FEM", "QT_TEC_FUND_COMP_MASC","QT_TEC_MEDIO_FEM",
            "QT_TEC_MEDIO_MASC", "QT_TEC_SUPERIOR_FEM", "QT_TEC_SUPERIOR_MASC", "QT_TEC_ESPECIALIZACAO_FEM",
            "QT_TEC_ESPECIALIZACAO_MASC", "QT_TEC_MESTRADO_FEM", "QT_TEC_MESTRADO_MASC", "QT_TEC_DOUTORADO_FEM", 
            "QT_TEC_DOUTORADO_MASC", "IN_ACESSO_PORTAL_CAPES", "IN_ACESSO_OUTRAS_BASES", "IN_REPOSITORIO_INSTITUCIONAL", 
            "IN_BUSCA_INTEGRADA", "IN_SERVICO_INTERNET", "IN_PARTICIPA_REDE_SOCIAL", "IN_CATALOGO_ONLINE", 
            "QT_PERIODICO_ELETRONICO", "QT_LIVRO_ELETRONICO", "VL_RECEITA_PROPRIA", "VL_TRANSFERENCIA", 
            "VL_OUTRA_RECEITA", "VL_DES_PESSOAL_REM_DOCENTE", "VL_DES_PESSOAL_REM_TECNICO", "VL_DES_PESSOAL_ENCARGO", 
            "VL_DES_CUSTEIO", "VL_DES_INVESTIMENTO", "VL_DES_PESQUISA", "VL_DES_OUTRAS")]


IES %>% dplyr::filter(., grepl('FEDERAL', NO_IES)) %>%  dplyr::filter(., !grepl('INSTITUTO|CENTRO', NO_IES)) %>%
  dplyr::filter(., !grepl('CAPITAL|DISTRITO', NO_IES)) -> teste

#summary(teste)

universidades = as.character(teste[,1])
cidades = as.character(teste[,2])
dados = teste[,-c(1,2)]

convert <- function(x) as.numeric(as.character(x))

# Padronizando:
dados %>% apply(., 2, convert) %>% scale -> dados

#  Clustering: Kmeans
set.seed(2)
clusters = kmeans(dados, 4)

# Spliting groups:

grupo_1 = teste[clusters$cluster == 1, ]
grupo_2 = teste[clusters$cluster == 2, ]
grupo_3 = teste[clusters$cluster == 3, ]
grupo_4 = teste[clusters$cluster == 4, ]

classificacao = cbind(universidades, cidades, clusters$cluster)

classificacao <- read_csv("classificacao.csv", 
                          locale = locale(encoding = "ISO-8859-1"))


# point colors
pal <- colorFactor(
  palette = c('red', 'blue', 'green', 'orange'),
  domain = classificacao$V3
)

# creating map
m <- leaflet(classificacao, width = "100%") %>% addTiles('http://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png', 
                              attribution='Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>') 
m %>% addCircleMarkers(lng = ~lon, lat = ~lat, fillColor = ~pal(V3), popup = ~universidades, fillOpacity = 0.7,
                       popupOptions = popupOptions(minWidth = 20, closeOnClick = FALSE, closeButton = TRUE))
```


# Clusters {.tabset}

## Group 1

```{r grupo1}
knitr::kable(grupo_1[,c("NO_IES", "NO_MUNICIPIO_IES")], row.names = FALSE)
```

## Group 2

```{r grupo2}
knitr::kable(grupo_2[,c("NO_IES", "NO_MUNICIPIO_IES")], row.names = FALSE)
```

## Group 3

```{r grupo3}
knitr::kable(grupo_3[,c("NO_IES", "NO_MUNICIPIO_IES")])
```

## Group 4

```{r grupo4}
knitr::kable(grupo_4[,c("NO_IES", "NO_MUNICIPIO_IES")])
```
